### ISSUE TITLE
How do I compile the source code

### ISSUE THREAD

**Issue by InsploitAdmin** [deaddlocust/LBI-Base#3]
I cannot compile the source code because pch.h is not there. How do i fix it?

**Comment by deaddlocust** [comment]
Make sure you compile the project as x86 release.
![image](https://user-images.githubusercontent.com/70506265/120821612-37f59e80-c588-11eb-9d1d-eef39f1acf70.png)

**Comment by InsploitAdmin** [comment]
Thanks!
