### ISSUE TITLE
Error with pch.h

### ISSUE THREAD

**Issue by nuldylan** [deaddlocust/LBI-Base#6]
Whenever I try to run or debug the project it leaves me with the following error:
https://cdn.discordapp.com/attachments/860955582520098859/869251618447695902/unknown.png

**Comment by deaddlocust** [comment]
You need to build in Release x86. 
![image](https://user-images.githubusercontent.com/70506265/127086330-644fbe3d-d40d-43de-b208-1f603aae3906.png)

Also, this is a DLL that is meant to be injected into Roblox. You can't run the DLL file directly.
